sonar.projectKey=devsecops-api
sonar.projectName=DevSecOps API
# Tell SonarQube to only scan our python application folder
sonar.sources=app/
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
